# Example extensions configuration
OrderNumberGenerator=SequenceNumberGenerator
OrderCreatePostProcessor=ExchangeRateOrderCreatePostProcessor
ShipmentCreatePostProcessor=ExchangeRateShipmentCreatePostProcessor
